"""empty message

Revision ID: 4435d89a6ece
Revises: 9c75a5cbf319
Create Date: 2020-03-16 18:42:54.922294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4435d89a6ece'
down_revision = '9c75a5cbf319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_suggestion_add_time'), 'suggestion', ['add_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_add_time'), table_name='suggestion')
    op.drop_column('suggestion', 'add_time')
    # ### end Alembic commands ###
