"""empty message

Revision ID: 65ab07cec83a
Revises: db6f7167ce06
Create Date: 2020-03-17 09:31:24.365042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ab07cec83a'
down_revision = 'db6f7167ce06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminlog', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_adminlog_add_time'), 'adminlog', ['add_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adminlog_add_time'), table_name='adminlog')
    op.drop_column('adminlog', 'add_time')
    # ### end Alembic commands ###
