"""empty message

Revision ID: 8cbb7592975a
Revises: f36e595c7d20
Create Date: 2020-03-05 15:37:06.348965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbb7592975a'
down_revision = 'f36e595c7d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlog')
    # ### end Alembic commands ###
