"""empty message

Revision ID: db6f7167ce06
Revises: 4435d89a6ece
Create Date: 2020-03-17 09:18:29.268823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6f7167ce06'
down_revision = '4435d89a6ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oplog', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_oplog_add_time'), 'oplog', ['add_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oplog_add_time'), table_name='oplog')
    op.drop_column('oplog', 'add_time')
    # ### end Alembic commands ###
