"""empty message

Revision ID: f36e595c7d20
Revises: cf368e18b311
Create Date: 2019-12-19 16:12:25.543650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f36e595c7d20'
down_revision = 'cf368e18b311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_area_add_time'), 'area', ['add_time'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=26), nullable=False),
    sa.Column('email', sa.String(length=26), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_scenic_add_time'), 'scenic', ['add_time'], unique=False)
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collect_add_time'), 'collect', ['add_time'], unique=False)
    op.create_table('travels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('scenic_id', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travels_add_time'), 'travels', ['add_time'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_travels_add_time'), table_name='travels')
    op.drop_table('travels')
    op.drop_index(op.f('ix_collect_add_time'), table_name='collect')
    op.drop_table('collect')
    op.drop_index(op.f('ix_scenic_add_time'), table_name='scenic')
    op.drop_table('scenic')
    op.drop_table('user')
    op.drop_index(op.f('ix_area_add_time'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
